import { defineConfig } from "zotero-plugin-scaffold";

import pkg from "./package.json";

export default defineConfig({
  source: ["src", "addon"],
  // Generated by watch:css; rewriting it must not restart the serve loop.
  watchIgnore: ["**/publishCoverStyles.generated.ts"],
  dist: ".scaffold/build",
  name: pkg.config.addonName,
  id: pkg.config.addonID,
  namespace: pkg.config.addonRef,
  updateURL: `https://github.com/{{owner}}/{{repo}}/releases/download/release/${
    pkg.version.includes("-") ? "update-beta.json" : "update.json"
  }`,
  xpiDownloadLink:
    "https://github.com/{{owner}}/{{repo}}/releases/download/v{{version}}/{{xpiName}}.xpi",

  build: {
    assets: ["addon/**/*.*"],
    define: {
      ...pkg.config,
      author: pkg.author,
      description: pkg.description,
      homepage: pkg.homepage,
      buildVersion: pkg.version,
      buildTime: "{{buildTime}}",
    },
    prefs: {
      prefix: pkg.config.prefsPrefix,
    },
    esbuildOptions: [
      {
        entryPoints: ["src/index.ts"],
        define: {
          __env__: `"${process.env.NODE_ENV}"`,
        },
        bundle: true,
        // Keep firefox115 so the bundle still runs on Zotero 7; Zotero 8–10
        // (Firefox 140) are a superset for the syntax we emit.
        target: "firefox115",
        outfile: `.scaffold/build/addon/content/scripts/${pkg.config.addonRef}.js`,
        jsx: "transform",
        jsxFactory: "h",
        jsxFragment: "Fragment",
      },
    ],
  },

  test: {
    watch: false,
    waitForPlugin: `() => !!(Zotero.${pkg.config.addonInstance} && Zotero.${pkg.config.addonInstance}.data && Zotero.${pkg.config.addonInstance}.data.initialized)`,
  },

  // If you need to see a more detailed log, uncomment the following line:
  // logLevel: "trace",
});
