import { homedir } from "node:os";

import { defineConfig } from "zotero-plugin-scaffold";

import pkg from "./package.json";

/** dotenv does not expand `~`; Node then treats it as a cwd-relative folder. */
function expandUserPath(value: string | undefined): string | undefined {
  if (value == null) return value;
  const trimmed = value.trim();
  if (!trimmed) return "";
  if (trimmed === "~") return homedir();
  if (trimmed.startsWith("~/") || trimmed.startsWith("~\\")) {
    return homedir() + trimmed.slice(1);
  }
  return trimmed;
}

for (const key of [
  "ZOTERO_PLUGIN_ZOTERO_BIN_PATH",
  "ZOTERO_PLUGIN_PROFILE_PATH",
  "ZOTERO_PLUGIN_DATA_DIR",
] as const) {
  const expanded = expandUserPath(process.env[key]);
  if (expanded !== undefined) process.env[key] = expanded;
}

export default defineConfig({
  source: ["src", "addon"],
  // Generated by watch:css; rewriting it must not restart the serve loop.
  watchIgnore: [
    "**/publishCoverStyles.generated.ts",
    "**/cssHash.generated.ts",
  ],
  dist: ".scaffold/build",
  name: pkg.config.addonName,
  id: pkg.config.addonID,
  namespace: pkg.config.addonRef,
  updateURL: `https://github.com/{{owner}}/{{repo}}/releases/download/release/${
    pkg.version.includes("-") ? "update-beta.json" : "update.json"
  }`,
  xpiDownloadLink:
    "https://github.com/{{owner}}/{{repo}}/releases/download/v{{version}}/{{xpiName}}.xpi",

  build: {
    assets: ["addon/**/*.*"],
    define: {
      ...pkg.config,
      author: pkg.author,
      description: pkg.description,
      homepage: pkg.homepage,
      buildVersion: pkg.version,
      buildTime: "{{buildTime}}",
    },
    prefs: {
      prefix: pkg.config.prefsPrefix,
    },
    esbuildOptions: [
      {
        entryPoints: ["src/index.ts"],
        define: {
          __env__: `"${process.env.NODE_ENV}"`,
        },
        bundle: true,
        // Keep firefox115 so the bundle still runs on Zotero 7; Zotero 8–10
        // (Firefox 140) are a superset for the syntax we emit.
        target: "firefox115",
        outfile: `.scaffold/build/addon/content/scripts/${pkg.config.addonRef}.js`,
        jsx: "transform",
        jsxFactory: "h",
        jsxFragment: "Fragment",
        // Jotai (and any React-shaped imports) resolve through Preact compat.
        // Do not wrap renderComponent roots in jotai Provider — default store
        // is shared across Syllabus / ItemPane / Gallery / Explorer.
        alias: {
          react: "preact/compat",
          "react-dom": "preact/compat",
        },
        banner: {
          // @dnd-kit/abstract needs bare AbortController + queueMicrotask;
          // chrome bootstrap sandboxes often lack both (and may lack `window`).
          js: `
(function () {
  var g = typeof globalThis !== "undefined" ? globalThis : null;
  var w = null;
  try {
    w = typeof window !== "undefined" ? window
      : Components.classes["@mozilla.org/appshell/appShellService;1"]
          .getService(Components.interfaces.nsIAppShellService).hiddenDOMWindow;
  } catch (e) {}
  if (g && typeof g.AbortController !== "function" && w && w.AbortController) {
    g.AbortController = w.AbortController;
    if (w.AbortSignal) g.AbortSignal = w.AbortSignal;
  }
  if (g && typeof g.queueMicrotask !== "function") {
    g.queueMicrotask = (w && typeof w.queueMicrotask === "function")
      ? w.queueMicrotask.bind(w)
      : function (cb) { Promise.resolve().then(cb); };
  }
})();
var AbortController = globalThis.AbortController;
var AbortSignal = globalThis.AbortSignal;
var queueMicrotask = globalThis.queueMicrotask;
`.replace(/\n/g, " "),
        },
      },
    ],
  },

  test: {
    watch: false,
    waitForPlugin: `() => !!(Zotero.${pkg.config.addonInstance} && Zotero.${pkg.config.addonInstance}.data && Zotero.${pkg.config.addonInstance}.data.initialized)`,
  },

  // If you need to see a more detailed log, uncomment the following line:
  // logLevel: "trace",
});
