// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'item-section-syllabus-head-text'
  | 'item-section-syllabus-sidenav-tooltip'
  | 'menu-toggle-bibliography'
  | 'panel-demo-header'
  | 'panel-demo-sidenav'
  | 'pref-compact-mode'
  | 'pref-enable'
  | 'pref-help'
  | 'pref-input'
  | 'pref-should-colour-syllabus-rows'
  | 'pref-show-bibliography'
  | 'pref-title'
  | 'prefs-table-detail'
  | 'prefs-table-title'
  | 'prefs-title'
  | 'startup-begin'
  | 'startup-finish'
  | 'tabpanel-lib-tab-label'
  | 'tabpanel-reader-tab-label';
