// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "enable": boolean;
      "showBibliography": boolean;
      "compactMode": boolean;
      "readerMode": boolean;
      "shouldColourSyllabusRows": boolean;
      "debugMode": boolean;
      "wpm": number;
      "latestTourVersion": number;
      "latestGalleryTourVersion": number;
      "defaultGalleryLayout": string;
      "defaultGallerySort": string;
      "defaultGalleryGroupBy": string;
      "myAnnotationsLayout": string;
      "myAnnotationsSort": string;
      "myAnnotationsGroupBy": string;
      "magazineTypeSize": string;
      "generateReadingScheduleCollection": boolean;
      "readingScheduleCollectionKey": string;
      "customIcons": boolean;
    };
  }
}
