// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "showBibliography": boolean;
      "defaultItemDensity": string;
      "readerMode": boolean;
      "shouldColourSyllabusRows": boolean;
      "debugMode": boolean;
      "wpm": number;
      "enableSyllabus": boolean;
      "enableGallery": boolean;
      "enableExplorer": boolean;
      "enableReadingSchedule": boolean;
      "enableAnnotations": boolean;
      "myAnnotationsCopyBlockquote": boolean;
      "myAnnotationsCopyCiteKey": boolean;
      "optionalFeaturesPromptDone": boolean;
      "latestTourVersion": number;
      "latestGalleryTourVersion": number;
      "defaultGalleryLayout": string;
      "defaultGallerySort": string;
      "defaultGalleryGroupBy": string;
      "myAnnotationsLayout": string;
      "myAnnotationsSort": string;
      "myAnnotationsGroupBy": string;
      "myAnnotationsOrder": string;
      "myAnnotationsColorFilter": string;
      "annotationsQuoteOrder": string;
      "galleryShowItemsWithoutAnnotations": boolean;
      "magazineTypeSize": string;
      "magazinePacking": string;
      "generateReadingScheduleCollection": boolean;
      "readingScheduleCollectionKey": string;
      "customIcons": boolean;
      "publishApiBaseUrl": string;
      "publishJwt": string;
      "publishUserId": string;
      "publishJwtExpiresAt": number;
      "defaultPriorities": string;
    };
  }
}
