import { execSync } from "child_process";
import { createHash } from "crypto";
import { readFileSync, writeFileSync, watch } from "fs";
import { fileURLToPath } from "url";
import { dirname, join } from "path";
import postcss from "postcss";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const rootDir = join(__dirname, "..");

const inputFile = join(rootDir, "src/tailwind.css");
const outputFile = join(rootDir, "addon/content/tailwind.css");
const hashFile = join(rootDir, "addon/content/tailwind-hash.json");
const galleryCoverFile = join(rootDir, "addon/content/galleryCover.css");
const publishShimFile = join(rootDir, "src/styles/publishCoverShim.css");
const publishCoverOut = join(
  rootDir,
  "src/utils/publishCoverStyles.generated.ts",
);

/**
 * Prefix every rule selector with `body.publish-layout` (skip keyframes).
 */
async function prefixPublishLayout(css) {
  const result = await postcss([
    {
      postcssPlugin: "prefix-publish-layout",
      Rule(rule) {
        let parent = rule.parent;
        while (parent) {
          if (parent.type === "atrule" && parent.name === "keyframes") {
            return;
          }
          parent = parent.parent;
        }
        rule.selectors = rule.selectors.map((selector) => {
          const trimmed = selector.trim();
          if (trimmed.startsWith("body.publish-layout")) {
            return trimmed;
          }
          return `body.publish-layout ${trimmed}`;
        });
      },
    },
  ]).process(css, { from: undefined });
  return result.css;
}

export async function generatePublishCoverStyles() {
  const galleryCss = readFileSync(galleryCoverFile, "utf8");
  const shimCss = readFileSync(publishShimFile, "utf8");
  const prefixed = await prefixPublishLayout(galleryCss);

  const combined = `${shimCss.trim()}\n\n/* From addon/content/galleryCover.css */\n${prefixed.trim()}\n`;

  const ts = `/**
 * Generated by scripts/build-css.js — do not edit.
 * Semantic rules: addon/content/galleryCover.css
 * Publish shim: src/styles/publishCoverShim.css
 */
export const PUBLISH_COVER_CSS = ${JSON.stringify(combined)};
`;

  writeFileSync(publishCoverOut, ts, "utf8");
  console.log(`✓ Generated publish cover CSS: ${publishCoverOut}`);
}

function buildTailwind() {
  execSync(`npx @tailwindcss/cli -i ${inputFile} -o ${outputFile}`, {
    stdio: "inherit",
    cwd: rootDir,
  });

  execSync(`npx prettier --write "${outputFile}"`, {
    stdio: "inherit",
    cwd: rootDir,
  });

  const cssContent = readFileSync(outputFile, "utf8");
  const hash = createHash("sha256")
    .update(cssContent)
    .digest("hex")
    .substring(0, 8);

  writeFileSync(hashFile, JSON.stringify({ hash, version: hash }), "utf8");
  execSync(`npx prettier --write "${hashFile}"`, {
    stdio: "inherit",
    cwd: rootDir,
  });

  console.log(`✓ Built Tailwind CSS: ${outputFile}`);
  console.log(`✓ CSS hash: ${hash}`);
}

export function watchPublishCoverStyles() {
  const targets = [galleryCoverFile, publishShimFile];
  let timer = null;
  const rebuild = () => {
    if (timer) clearTimeout(timer);
    timer = setTimeout(() => {
      generatePublishCoverStyles().catch((err) => {
        console.error("Error generating publish cover CSS:", err);
      });
    }, 100);
  };
  for (const target of targets) {
    watch(target, rebuild);
  }
  console.log("✓ Watching galleryCover.css + publishCoverShim.css");
  rebuild();
}

const invokedAsCli =
  process.argv[1] && process.argv[1].endsWith("build-css.js");

if (invokedAsCli) {
  const watchOnly = process.argv.includes("--watch-publish-cover");
  try {
    if (watchOnly) {
      watchPublishCoverStyles();
    } else {
      buildTailwind();
      await generatePublishCoverStyles();
    }
  } catch (err) {
    console.error("Error building CSS:", err);
    process.exit(1);
  }
}
